project_id = "urqxzhvqwkgqrdsruafb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_confirmations = false

[db]
enabled = true
port = 54322
major_version = 15

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
s3_max_part_size = "5MiB"
s3_upload_part_size = "6MiB"
create_image_transformations = true

[functions.generate-upload-url]
verify_jwt = true

[functions.process-illustration]
verify_jwt = true