// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urqxzhvqwkgqrdsruafb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVycXh6aHZxd2tncXJkc3J1YWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjY2NDYsImV4cCI6MjA3MTgwMjY0Nn0.TlBIedv1xzGwrDVEUkOeiUJyfe1zdOdiToX_v7ezIPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});